server:
  port: 8080
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER

spring:
  banner:
    location: classpath:custom-banner.txt
  flyway:
    enabled: true
    encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: dbuser
    password: dbpass